version: '3.3'
networks:
  thesis:

services:

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: thesis
      POSTGRES_USER: thesis
      POSTGRES_PASSWORD: thesis
      POSTGRES_INITDB_ARGS: -A password
    ports:
      - "5433:5432"
    networks:
      - thesis
