version: '3.3'
networks:
  thesis:

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: thesis
      POSTGRES_USER: thesis
      POSTGRES_PASSWORD: thesis
      POSTGRES_INITDB_ARGS: -A password
    ports:
      - "5433:5432"
    networks:
      - thesis
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: gunicorn service.wsgi:application --bind 0.0.0.0:8000
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ./working_dir/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - service/.env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - CERTIFICATE_PRIVATE_KEY_PASSWORD=${CERTIFICATE_PRIVATE_KEY_PASSWORD}
    depends_on:
      - postgres
    networks:
      - thesis


volumes:
  postgres_data:
