version: '3.3'
networks:
  thesis:
    driver: bridge

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: thesis
      POSTGRES_USER: thesis
      POSTGRES_PASSWORD: thesis
      POSTGRES_INITDB_ARGS: -A password
    restart: always
    ports:
      - "5433:5432"
    networks:
      - thesis
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: ./app
    command: gunicorn service.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - CERTIFICATE_PRIVATE_KEY_PASSWORD=${CERTIFICATE_PRIVATE_KEY_PASSWORD}
      - BLOCKCHAIN_HOST=host.docker.internal
#      - BLOCKCHAIN_CLI_GLOBAL_FLAGS=--home /run/secrets/.thesis
    depends_on:
      - postgres
    networks:
      - thesis
    volumes:
      - static_volume:/home/app/web/staticfiles
      - files_volume:/home/app/web/media
    secrets:
      - cert
      - .thesis
    restart: always

  blockchain_websocket:
    build: ./app
    command: python manage.py start_websocket
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - CERTIFICATE_PRIVATE_KEY_PASSWORD=${CERTIFICATE_PRIVATE_KEY_PASSWORD}
      - BLOCKCHAIN_HOST=node-1
    #      - BLOCKCHAIN_CLI_GLOBAL_FLAGS=--home /run/secrets/.thesis
    depends_on:
      - postgres
      - node-1
    networks:
      - thesis
    secrets:
      - cert
      - .thesis
    restart: always

  nginx:
    # ngnix is responsible for https communication between world and services(web and node-1)
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    networks:
      - thesis
    ports:
      - "1347:80"
      - "1337:443"
      - "1317:317"
      - "16657:16657"
      - "26657:6657"
      - "26656:6656"
    depends_on:
      - web
      - node-1
    secrets:
      - cert
    restart: always

  node-1:
    image: thesis-blockchain:latest
    expose:
      - 26657
      - 1317
      - 26656
      - 9090
    command: ./thesisd start --rpc.laddr tcp://0.0.0.0:26657
    env_file:
      - blockchain/node-1.env
    volumes:
      - node_1_data:/home/app/
    networks:
      - thesis
    restart: always

  node-2:
    image: thesis-blockchain:latest
    expose:
      - 26657
      - 1317
      - 26656
      - 9090
    ports:
      - "26659:26657"
    command: ./thesisd start --rpc.laddr tcp://0.0.0.0:26657
    env_file:
      - blockchain/node-2.env
    volumes:
      - node_2_data:/home/app/
    networks:
      - thesis
    depends_on:
      - node-1
    restart: always


volumes:
  postgres_data:
  static_volume:
  node_1_data:
  node_2_data:
  files_volume:

secrets:
  cert:
    file: ./cert
  .thesis:
    file: /home/przemek/.thesis
