# Generated by Django 4.1.3 on 2022-12-01 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='OwnedIdentities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_bytes', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='date created')),
            ],
        ),
    ]
