# Generated by Django 4.1.3 on 2022-12-08 09:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('blockchain_address', models.CharField(max_length=45, unique=True, verbose_name='address')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('verification_status', models.IntegerField(choices=[(1, 'Email verification'), (2, 'Blockchain address verification'), (3, 'Verified')], default=1, verbose_name='verification status')),
                ('verification_token', models.UUIDField(default=uuid.UUID('4b6bd9e2-e414-499a-a9d4-492c653fd3ce'), verbose_name='verification token')),
                ('service_verification_tx_hash', models.CharField(max_length=256, verbose_name='service_tx')),
                ('user_verification_tx_hash', models.CharField(max_length=256, verbose_name='user_tx')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='date created')),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='date modified')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
