# Generated by Django 4.1.3 on 2022-12-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='email',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='verification_token',
        ),
        migrations.AlterField(
            model_name='identity',
            name='blockchain_address',
            field=models.CharField(default=None, max_length=45, null=True, unique=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='service_verification_tx_hash',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='service_tx'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='user_verification_tx_hash',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='user_tx'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='verification_status',
            field=models.IntegerField(choices=[(1, 'Blockchain address verification'), (2, 'Verified')], default=1, verbose_name='verification status'),
        ),
    ]
