# Generated by Django 4.1.3 on 2023-01-07 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_der', models.BinaryField(null=True)),
                ('identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.identity')),
            ],
        ),
    ]
