# Generated by Django 4.1.3 on 2022-12-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_identity_email_remove_identity_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='user_verification_tx_hash',
        ),
        migrations.AddField(
            model_name='identity',
            name='user_verification_tx_height',
            field=models.IntegerField(default=None, null=True, verbose_name='user_tx'),
        ),
    ]
