# Generated by Django 4.1.3 on 2022-12-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='fileHashBase64',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
