# Generated by Django 4.1.3 on 2022-12-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lastBlockchainHeight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
