# Generated by Django 4.1.3 on 2022-12-28 22:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_filehashbase64_storedfile_filehashbase16'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None),
        ),
    ]
