# Generated by Django 4.1.3 on 2022-12-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_lastblockchainheight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='lastBlockchainHeight',
            new_name='lastEditHeight',
        ),
    ]
