# Generated by Django 4.1.3 on 2022-12-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='fileHashBase16',
            field=models.CharField(max_length=64),
        ),
    ]
