# Generated by Django 4.1.3 on 2023-01-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='ackTxHash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
